language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - 'node_modules'
notifications:
  email: true
node_js:
  - '8'
install:
  - yarn install --network-timeout 1000000
script:
  - commitlint-travis
  - yarn test
  - yarn coverage
before_deploy:
  - yarn build
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
