language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - "node_modules"
notifications:
  email: true
node_js:
  - '8'
script:
  - yarn test
before_deploy:
  - yarn build
  - yarn coverage
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
